title: No ICE in Schools
description: Advocacy resources for keeping schools safe from ICE
baseurl: "/NoICEinSchools"
url: "https://joshuagjohanson.github.io"
markdown: kramdown
permalink: pretty

# GitHub Pages settings
theme: jekyll-theme-primer
plugins:
  - jekyll-feed
  - jekyll-seo-tag